# Generated by Django 3.0.1 on 2020-01-24 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_Title', models.CharField(max_length=40)),
                ('job_discription', models.CharField(max_length=100)),
                ('job_Catagory', models.CharField(max_length=40)),
            ],
            options={
                'permissions': (('can_post_job', 'Can post a job'),),
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resume/pdfs')),
                ('resume_QRcode', models.ImageField(blank=True, null=True, upload_to='resume/images')),
                ('YearUploaded', models.DateField(null=True)),
            ],
            options={
                'permissions': (('uploadResume', 'can upload Resume'), ('modifyResume', 'can modify Resume')),
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='courseworkapp.Company')),
                ('jobs', models.ManyToManyField(to='courseworkapp.Job')),
            ],
        ),
        migrations.CreateModel(
            name='JobSeeker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('resumes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='courseworkapp.Resume')),
                ('seeker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='jobs',
            field=models.ManyToManyField(to='courseworkapp.Job'),
        ),
    ]
