# Generated by Django 2.2.7 on 2020-01-11 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courseworkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=50)),
                ('resume', models.FileField(upload_to='resume/pdfs')),
                ('resume_QRcode', models.ImageField(blank=True, null=True, upload_to='resume/images')),
            ],
        ),
    ]
